CREATE TABLE hib_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(100) NOT NULL UNIQUE,
    email               VARCHAR(100) UNIQUE,
    password            VARCHAR(255) NOT NULL,
    avatar_url          VARCHAR(255),
    status              VARCHAR(50) DEFAULT 'ACTIVE',
    theme_dark          INT  DEFAULT 0,
    email_notifications INT  DEFAULT 1,
    language            VARCHAR(50) DEFAULT 'EN',
    current_organization_id BIGINT DEFAULT 0,
    bio                 TEXT,
    created_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted             INT  DEFAULT 0
);

CREATE TABLE hib_organization
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL UNIQUE,
    description     TEXT,
    owner_id        BIGINT       NOT NULL,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0,
    status          VARCHAR(50) DEFAULT 'ACTIVE',
    published       INT  DEFAULT 0,
    max_members     INT         DEFAULT 50,
    current_members INT         DEFAULT 0
);

CREATE TABLE hib_organization_member
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    user_id         BIGINT NOT NULL,
    role            VARCHAR(50) DEFAULT 'MEMBER',
    status          VARCHAR(50) DEFAULT 'ACTIVE',
    joined_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0,
    CONSTRAINT uk_org_user UNIQUE (organization_id, user_id)
);

CREATE TABLE hib_org_invite
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL,
    inviter_id      BIGINT NOT NULL,
    invite_code     VARCHAR(100) UNIQUE,
    role            VARCHAR(50) DEFAULT 'MEMBER',
    max_uses        INT         DEFAULT 1,
    used_count      INT         DEFAULT 0,
    expires_at      TIMESTAMP,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0
);

CREATE TABLE hib_knowledge_base
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    type            VARCHAR(50) DEFAULT 'PRIVATE',
    owner_id        BIGINT       NOT NULL,
    organization_id BIGINT,
    cover_url       VARCHAR(255),
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT  DEFAULT 0
);

CREATE TABLE hib_knowledge_base_collaborator
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT NOT NULL,
    user_id           BIGINT NOT NULL,
    role              VARCHAR(50) DEFAULT 'EDITOR',
    joined_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted           INT  DEFAULT 0,
    CONSTRAINT uk_kb_user UNIQUE (knowledge_base_id, user_id)
);

CREATE TABLE hib_document
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id  BIGINT       NOT NULL,
    parent_id          BIGINT      DEFAULT NULL,
    title              VARCHAR(255) NOT NULL,
    type               VARCHAR(50) DEFAULT 'DOC',
    owner_id           BIGINT       NOT NULL,
    sort_order         INT         DEFAULT 0,
    status             VARCHAR(50) DEFAULT 'ACTIVE',
    version            INT         DEFAULT 1,
    level              INT         DEFAULT 0,
    published          INT  DEFAULT 0,
    current_version_id BIGINT      DEFAULT NULL,
    metadata           JSON,
    created_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted            INT  DEFAULT 0
);

CREATE TABLE hib_document_version
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    version     INT    NOT NULL,
    content     LONGTEXT,
    editor_id   BIGINT,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT DEFAULT 0
);

CREATE TABLE hib_document_comment
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    user_id     BIGINT NOT NULL,
    content     TEXT   NOT NULL,
    anchor      JSON,
    status      VARCHAR(50) DEFAULT 'ACTIVE',
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT  DEFAULT 0
);

CREATE TABLE hib_operation_log
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        VARCHAR(100) NOT NULL,
    description TEXT,
    user_id     BIGINT,
    operator    VARCHAR(100) NOT NULL,
    success     INT      NOT NULL,
    params      TEXT,
    result      TEXT,
    timestamp   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted     TINYINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP              DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP              DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hib_document_favorite
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    document_id  BIGINT NOT NULL,
    favorited_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted      INT DEFAULT 0,
    CONSTRAINT uk_user_doc UNIQUE (user_id, document_id)
);

CREATE TABLE hib_notification
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_id       BIGINT                            NOT NULL,
    type          VARCHAR(32)                       NOT NULL,
    title         VARCHAR(255)                      NOT NULL,
    content       TEXT,
    level         VARCHAR(32)                                DEFAULT 'NORMAL',
    is_read       INT                           NOT NULL DEFAULT FALSE,
    business_id   varchar(255)                               DEFAULT NULL,
    business_type VARCHAR(64)                                DEFAULT NULL,
    extra_data    JSON                                       DEFAULT NULL,
    send_time     TIMESTAMP                                   DEFAULT NULL,
    read_time     TIMESTAMP                                   DEFAULT NULL,
    deleted       TINYINT                           NOT NULL DEFAULT 0,
    created_at    TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP                                   DEFAULT CURRENT_TIMESTAMP ,
    PRIMARY KEY (id)
);

CREATE TABLE hib_tag
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    color      VARCHAR(20) DEFAULT '#CCCCCC',
    created_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted    INT  DEFAULT 0
);

CREATE TABLE hib_document_tag
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL,
    tag_id      BIGINT NOT NULL,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT DEFAULT 0,
    CONSTRAINT uk_doc_tag UNIQUE (document_id, tag_id)
);

CREATE TABLE hib_document_template
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    description TEXT,
    content     LONGTEXT     NOT NULL,
    creator_id  BIGINT       NOT NULL,
    scope       VARCHAR(50) DEFAULT 'PRIVATE',
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT  DEFAULT 0
);

CREATE TABLE hib_document_permission
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT      NOT NULL,
    user_id     BIGINT      NOT NULL,
    permission  VARCHAR(50) NOT NULL,
    granted_by  BIGINT,
    granted_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted     INT DEFAULT 0,
    CONSTRAINT uk_doc_user UNIQUE (document_id, user_id)
);

CREATE TABLE hib_webhook
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT,
    event_type      VARCHAR(100) NOT NULL,
    target_url      VARCHAR(255) NOT NULL,
    enabled         INT    DEFAULT TRUE,
    secret          VARCHAR(255),
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP ,
    deleted         INT DEFAULT 0
);