/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiFileDocumentOutline: typeof import('~icons/mdi/file-document-outline')['default']
    IconMdiFolderOutline: typeof import('~icons/mdi/folder-outline')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    Layout: typeof import('./src/layout/Layout.vue')['default']
    LeftSidebar: typeof import('./src/components/LeftSidebar.vue')['default']
    NestedOutlineEditor: typeof import('./src/components/NestedOutlineEditor.vue')['default']
    RightSidebar: typeof import('./src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
