/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    AvatarGroup: typeof import('./src/components/AvatarGroup.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    CustomModal: typeof import('./src/components/CustomModal.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronLeft: typeof import('~icons/mdi/chevron-left')['default']
    IconMdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    IconMdiFileDocumentOutline: typeof import('~icons/mdi/file-document-outline')['default']
    IconMdiFolderOutline: typeof import('~icons/mdi/folder-outline')['default']
    IconMdiHome: typeof import('~icons/mdi/home')['default']
    Layout: typeof import('./src/layout/Layout.vue')['default']
    LeftSidebar: typeof import('./src/components/LeftSidebar.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem.vue')['default']
    NestedOutlineEditor: typeof import('./src/components/NestedOutlineEditor.vue')['default']
    Notify: typeof import('./src/components/Notify.vue')['default']
    NotifyContainer: typeof import('./src/components/NotifyContainer.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RightSidebar: typeof import('./src/components/RightSidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SiderMenu: typeof import('./src/components/SiderMenu.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    VegaLiteTest: typeof import('./src/components/VegaLiteTest.vue')['default']
    WChart: typeof import('./src/components/WChart.vue')['default']
  }
}
